In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns #for beatiful visualizations
%matplotlib inline 
import scipy.stats as scs #for statistics
import operator
from scipy.stats import chi2_contingency
import matplotlib.ticker as ticker

Dans cette partie nous allons efféctuer les transformation des nos variables de sortie et effetuer diverses transformations possible pour notre travil

In [2]:
dataset=pd.read_csv("DatasetOut.csv",index_col="Unnamed: 0")

In [3]:
dataset.shape

(9606, 9)

In [13]:
dataset.columns

Index([u'IDENTIFICATION', u'ACADYEAR', u'PERC1', u'MENT1', u'PERC2', u'MENT2',
       u'FAC', u'OPT', u'PROM'],
      dtype='object')

pour une premierre iteration nous allons travailler avec les données de la facultée de médecine et esuite ettendre notre modèlz aux autres facultées

In [4]:
medeDataset=dataset.loc[dataset.FAC=='FM']

In [5]:
medeDataset.head(5)

,IDENTIFICATION,ACADYEAR,PERC1,MENT1,PERC2,MENT2,FAC,OPT,PROM
34,1670,2014-2015,65.099998,S,NaN,NaN,FM,Bio-Méd,G1
35,1670,2015-2016,57.099998,A,59.200001,S,FM,Bio-Méd,G2
6871,9841,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1
6917,9867,2014-2015,NaN,AA,59.200001,S,FM,Bio-Méd,G1
6918,9867,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G2

In [6]:
medeDataset.rename(columns={'IDENTIFICATION':'ID'},inplace=True)

/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/pandas/core/frame.py:2834: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

Maitenant nous allons travailler sur le groupement des nos données et la creation des nouvelles variables , après cetrainnes rechreches nous avons pu conclure que pour mesurer les performances des étudiants à l'université une des métriques utilisé est le GPA(culmutative grade point average) [site note from atricles] ainsi nous allons calculer la moyenne des points des étudiants , ensuite nous calculerons les éches , ensuite pourcentage de distinctions enfin nous evaluerons le pourcentage des satisfactions , à coté de cela nous allons ajouter le nombre des fois qu'il est passé en prémiere session.

In [7]:
dataset.MENT2.value_counts().index

Index([u'S', u'A', u'AA', u'D', u'NAF', u'ADM', u'ADSTM', u'ADST', u'ADTFC',
       u'ANAF', u'AR', u'ADSTFC', u'GD'],
      dtype='object')

In [8]:
SuccefullMent=['S']
PartialSuccess=['ADM', 'ADTFC', 'ADSTM', 'ADSTFC', 'ADST']
Distinction=['D','GD']
FailSession=['AA','AR','nan']
FailureMention=['A','NAF','ANAF']

In [9]:
def calculateSucess(x):
    """this function will check if a student pass of fail in an aacademic year"""
    if str(x['MENT2']) in FailSession+FailureMention and (str(x['MENT1']) not in SuccefullMent+PartialSuccess+Distinction):
        return pd.Series(True)
    else :
        return pd.Series(False)

In [10]:
Echec=medeDataset.apply(calculateSucess,axis=1)

In [53]:
Echec[:6]

          0
34    False
35    False
6871   True
6917  False
6918   True
6937  False

In [54]:
medeDataset[:6]

        ID   ACADYEAR      PERC1 MENT1      PERC2 MENT2 FAC      OPT PROM
34    1670  2014-2015  65.099998     S        NaN   NaN  FM  Bio-Méd   G1
35    1670  2015-2016  57.099998     A  59.200001     S  FM  Bio-Méd   G2
6871  9841  2014-2015        NaN    AA        NaN    AA  FM  Bio-Méd   G1
6917  9867  2014-2015        NaN    AA  59.200001     S  FM  Bio-Méd   G1
6918  9867  2015-2016        NaN    AA        NaN     A  FM  Bio-Méd   G2
6937  9879  2014-2015  58.200001     A  64.199997     S  FM  Bio-Méd   G1

In [11]:
def calculateSatistisfation(x):
    """this function will check if a student pass of fail in an aacademic year"""
    if x['MENT1'] in SuccefullMent+PartialSuccess or x['MENT2']in SuccefullMent+PartialSuccess:
        return pd.Series(True)
    else :
        return pd.Series(False)

In [12]:
Satisfaction=medeDataset.apply(calculateSatistisfation,axis=1)

In [13]:
def calculateDistinCtion(x):
    """this function will check if a student pass of fail in an aacademic year"""
    if x['MENT1'] in Distinction or x['MENT2']in Distinction:
        return pd.Series(True)
    else :
        return pd.Series(False)

In [14]:
DistinctionStuden=medeDataset.apply(calculateDistinCtion,axis=1)

In [15]:
DistinctionStuden.loc[DistinctionStuden.get(0)==True]

         0
7358  True
7359  True
7483  True
7598  True
8104  True
8711  True
8713  True
9185  True

In [16]:
medeDataset.loc[DistinctionStuden.get(0)==True]

         ID   ACADYEAR      PERC1 MENT1      PERC2 MENT2 FAC      OPT PROM
7358  10126  2014-2015  71.500000     D        NaN   NaN  FM  Bio-Méd   G1
7359  10126  2015-2016  72.500000     D        NaN   NaN  FM  Bio-Méd   G2
7483  10197  2015-2016  73.599998     D        NaN   NaN  FM  Bio-Méd   G2
7598  10263  2015-2016  72.400002     D        NaN   NaN  FM  Bio-Méd   G2
8104  10577  2015-2016  73.300003     D        NaN   NaN  FM  Bio-Méd   G2
8711  11269  2015-2016  74.000000     D        NaN   NaN  FM  Bio-Méd   G1
8713  11272  2015-2016  71.699997     D        NaN   NaN  FM  Bio-Méd   G1
9185  11767  2015-2016        NaN    AA  70.300003     D  FM  Bio-Méd   G1

In [17]:
def calculatePass1estSes(x):
    """this function will check if a student pass of fail in an aacademic year"""
    if x['MENT1'] in SuccefullMent+PartialSuccess+Distinction:
        return pd.Series(True)
    else :
        return pd.Series(False)

In [18]:
PassAstSess=medeDataset.apply(calculatePass1estSes,axis=1)

In [19]:
def calculatePourcenatge(x):
    """this function will check if a student pass of fail in an aacademic year"""
    if x['MENT1'] in SuccefullMent+Distinction:
        return pd.Series(x['PERC1'])
    elif x['MENT2'] in SuccefullMent+Distinction :
        return pd.Series(x['PERC2'])
    else:
        return pd.Series(x['PERC2'])

In [20]:
FinalGrade=medeDataset.apply(calculatePourcenatge,axis=1)

In [68]:
PassAstSess

          0
34     True
35    False
6871  False
6917  False
6918  False
6937  False
6938   True
6949   True
6950  False
6955  False
6956  False
6987  False
6998  False
6999   True
7000   True
7001   True
7044  False
7045   True
7058  False
7087  False
7102  False
7106  False
7107   True
7116  False
7132  False
7139  False
7140   True
7145   True
7146  False
7158  False
...     ...
9357   True
9370  False
9392  False
9402   True
9404  False
9414  False
9420  False
9421  False
9426   True
9433  False
9461   True
9469  False
9470  False
9482  False
9490  False
9491   True
9493  False
9495  False
9496  False
9498  False
9500   True
9508   True
9512  False
9522  False
9523  False
9530  False
9535  False
9538  False
9552  False
9598  False

[375 rows x 1 columns]

In [21]:
medeDataset.loc[FinalGrade.isnull().get(0)==True]

         ID   ACADYEAR  PERC1 MENT1  PERC2 MENT2 FAC      OPT PROM
6871   9841  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
6918   9867  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G2
7087   9965  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7102   9975  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7116   9983  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7166  10012  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7337  10114  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7398  10150  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7408  10155  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G2
7418  10161  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7523  10222  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7554  10239  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G2
7556  10240  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G2
7638  10289  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7834  10409  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G2
7836  10411  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7852  10421  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
7980  10500  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8062  10550  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8106  10579  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8176  10618  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8198  10631  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8200  10632  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8201  10632  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
8259  10673  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8378  10746  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8438  10783  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8453  10793  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8515  10833  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8550  10854  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8559  10859  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
8568  10865  2014-2015    NaN    AA    NaN    AA  FM  Bio-Méd   G1
8620  10897  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G2
8677  11132  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
8725  11286  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
8772  11337  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
8773  11338  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
9033  11610  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
9194  11776  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
9214  11798  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
9414  12062  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
9469  12119  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
9523  12175  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1
9538  12191  2015-2016    NaN    AA    NaN     A  FM  Bio-Méd   G1

In [22]:
medeDataset['Satisfaction']=Satisfaction
medeDataset['echec']=Echec
medeDataset['distinction']=DistinctionStuden
medeDataset['Pass1stSession']=PassAstSess
medeDataset['PercFinal']=FinalGrade

/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [23]:
medeDataset.loc[:65]

,ID,ACADYEAR,PERC1,MENT1,PERC2,MENT2,FAC,OPT,PROM,Satisfaction,echec,distinction,Pass1stSession,PercFinal
34,1670,2014-2015,65.099998,S,NaN,NaN,FM,Bio-Méd,G1,True,False,False,True,65.099998
35,1670,2015-2016,57.099998,A,59.200001,S,FM,Bio-Méd,G2,True,False,False,False,59.200001

In [24]:
medeDataset.PercFinal=medeDataset.PercFinal.apply(lambda x: np.random.choice([x for x in range(45,53)]) if (np.isnan(x)) else x)

/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/pandas/core/generic.py:2773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [25]:
len(medeDataset.loc[medeDataset.Pass1stSession==True])

97

In [26]:
medeDataset.head(8)

,ID,ACADYEAR,PERC1,MENT1,PERC2,MENT2,FAC,OPT,PROM,Satisfaction,echec,distinction,Pass1stSession,PercFinal
34,1670,2014-2015,65.099998,S,NaN,NaN,FM,Bio-Méd,G1,True,False,False,True,65.099998
35,1670,2015-2016,57.099998,A,59.200001,S,FM,Bio-Méd,G2,True,False,False,False,59.200001
6871,9841,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,52.000000
6917,9867,2014-2015,NaN,AA,59.200001,S,FM,Bio-Méd,G1,True,False,False,False,59.200001
6918,9867,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G2,False,True,False,False,49.000000
6937,9879,2014-2015,58.200001,A,64.199997,S,FM,Bio-Méd,G1,True,False,False,False,64.199997
6938,9879,2015-2016,58.900002,S,NaN,NaN,FM,Bio-Méd,G2,True,False,False,True,58.900002
6949,9887,2014-2015,60.000000,S,NaN,NaN,FM,Bio-Méd,G1,True,False,False,True,60.000000

continous avec le calcul du ratio.

In [44]:
medeDataset.loc[medeDataset.echec==True]['']

,ID,ACADYEAR,PERC1,MENT1,PERC2,MENT2,FAC,OPT,PROM,Satisfaction,echec,distinction,Pass1stSession,PercFinal
6871,9841,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,52.000000
6918,9867,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G2,False,True,False,False,49.000000
6987,9909,2014-2015,NaN,AA,52.000000,A,FM,Bio-Méd,G1,False,True,False,False,52.000000
7087,9965,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,47.000000
7102,9975,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,51.000000
7116,9983,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,47.000000
7132,9993,2014-2015,NaN,AA,52.700001,A,FM,Bio-Méd,G1,False,True,False,False,52.700001
7166,10012,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,46.000000
7337,10114,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,48.000000
7362,10128,2014-2015,NaN,AA,49.799999,A,FM,Bio-Méd,G1,False,True,False,False,49.799999
7398,10150,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,48.000000
7408,10155,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G2,False,True,False,False,48.000000
7418,10161,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,48.000000
7450,10178,2015-2016,NaN,AA,53.599998,A,FM,Bio-Méd,G2,False,True,False,False,53.599998
7467,10187,2014-2015,51.000000,A,55.400002,A,FM,Bio-Méd,G1,False,True,False,False,55.400002
7497,10207,2014-2015,NaN,AA,49.700001,A,FM,Bio-Méd,G1,False,True,False,False,49.700001
7523,10222,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,45.000000
7533,10228,2014-2015,NaN,AA,53.799999,A,FM,Bio-Méd,G1,False,True,False,False,53.799999
7554,10239,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G2,False,True,False,False,45.000000
7556,10240,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G2,False,True,False,False,49.000000
7603,10266,2015-2016,49.400002,A,51.599998,A,FM,Bio-Méd,G2,False,True,False,False,51.599998
7633,10284,2014-2015,NaN,AA,45.700001,A,FM,Bio-Méd,G1,False,True,False,False,45.700001
7638,10289,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,49.000000
7648,10294,2015-2016,NaN,AA,48.000000,A,FM,Bio-Méd,G2,False,True,False,False,48.000000
7694,10324,2015-2016,NaN,AA,53.400002,A,FM,Bio-Méd,G2,False,True,False,False,53.400002
7830,10407,2015-2016,NaN,AA,53.400002,A,FM,Bio-Méd,G2,False,True,False,False,53.400002
7834,10409,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G2,False,True,False,False,46.000000
7836,10411,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,46.000000
7852,10421,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,47.000000
7980,10500,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,47.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8453,10793,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,46.000000
8503,10825,2014-2015,NaN,AA,54.299999,A,FM,Bio-Méd,G1,False,True,False,False,54.299999
8505,10826,2015-2016,52.000000,A,53.700001,A,FM,Bio-Méd,G2,False,True,False,False,53.700001
8515,10833,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,50.000000
8516,10833,2015-2016,NaN,AA,56.799999,A,FM,Bio-Méd,G1,False,True,False,False,56.799999
8550,10854,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,50.000000
8558,10859,2014-2015,NaN,AA,57.000000,A,FM,Bio-Méd,G1,False,True,False,False,57.000000
8559,10859,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,48.000000
8568,10865,2014-2015,NaN,AA,NaN,AA,FM,Bio-Méd,G1,False,True,False,False,50.000000
8607,10888,2015-2016,NaN,AA,52.599998,A,FM,Bio-Méd,G2,False,True,False,False,52.599998
8620,10897,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G2,False,True,False,False,49.000000
8634,10906,2015-2016,NaN,AA,50.500000,A,FM,Bio-Méd,G2,False,True,False,False,50.500000
8676,11132,2014-2015,NaN,AA,45.900002,A,FM,Bio-Méd,G1,False,True,False,False,45.900002
8677,11132,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,46.000000
8725,11286,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,48.000000
8757,11321,2015-2016,47.799999,A,53.500000,A,FM,Bio-Méd,G1,False,True,False,False,53.500000
8772,11337,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,46.000000
8773,11338,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,52.000000
9033,11610,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,45.000000
9121,11702,2015-2016,NaN,AA,55.099998,A,FM,Bio-Méd,G1,False,True,False,False,55.099998
9143,11724,2015-2016,NaN,AA,46.400002,A,FM,Bio-Méd,G1,False,True,False,False,46.400002
9194,11776,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,47.000000
9214,11798,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,49.000000
9392,12039,2015-2016,NaN,AA,48.700001,A,FM,Bio-Méd,G1,False,True,False,False,48.700001
9414,12062,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,45.000000
9469,12119,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,48.000000
9470,12120,2015-2016,52.400002,A,55.000000,A,FM,Bio-Méd,G1,False,True,False,False,55.000000
9522,12174,2015-2016,NaN,AA,42.000000,A,FM,Bio-Méd,G1,False,True,False,False,42.000000
9523,12175,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,46.000000
9538,12191,2015-2016,NaN,AA,NaN,A,FM,Bio-Méd,G1,False,True,False,False,51.000000

In [45]:
medeDataset.columns

Index([u'ID', u'ACADYEAR', u'PERC1', u'MENT1', u'PERC2', u'MENT2', u'FAC',
       u'OPT', u'PROM', u'Satisfaction', u'echec', u'distinction',
       u'Pass1stSession', u'PercFinal'],
      dtype='object')

In [69]:
def calculateReussiteDistin(x):
    """this function will check if a student pass of fail in an aacademic year"""
    if x['echec']==False and x['distinction']==True and x['Satisfaction']==False:
        """ceux qui ont distinguer"""
        if x['Pass1stSession']==True:
            """en premiere session"""
            return pd.Series(True)
        elif x['Pass1stSession']==False:
            """en seconde session"""
            return pd.Series(True)
    
    elif x['echec']==False and x['distinction']==False and x['Satisfaction']==True:
        if x['Pass1stSession']==True:
            """en premiere session"""
            return pd.Series(False)
        elif x['Pass1stSession']==False:
            """en seconde session"""
            return pd.Series(False)
    else :
        return pd.Series(False)

In [64]:
def calculateReussite1Sessi(x):
    """this function will check if a student pass of fail in an aacademic year"""
    if x['echec']==False and x['distinction']==True and x['Satisfaction']==False:
        """ceux qui ont distinguer"""
        if x['Pass1stSession']==True:
            """en premiere session"""
            return pd.Series(True)
        elif x['Pass1stSession']==False:
            """en seconde session"""
            return pd.Series(False)
    
    elif x['echec']==False and x['distinction']==False and x['Satisfaction']==True:
        if x['Pass1stSession']==True:
            """en premiere session"""
            return pd.Series(True)
        elif x['Pass1stSession']==False:
            """en seconde session"""
            return pd.Series(False)
    else :
        return pd.Series(False)

In [70]:
ReusiteDistinc=medeDataset.apply(calculateReussiteDistin,axis=1)

In [72]:
medeDataset.loc[ReusiteDistinc.get(0)==True]

,ID,ACADYEAR,PERC1,MENT1,PERC2,MENT2,FAC,OPT,PROM,Satisfaction,echec,distinction,Pass1stSession,PercFinal
7358,10126,2014-2015,71.500000,D,NaN,NaN,FM,Bio-Méd,G1,False,False,True,True,71.500000
7359,10126,2015-2016,72.500000,D,NaN,NaN,FM,Bio-Méd,G2,False,False,True,True,72.500000
7483,10197,2015-2016,73.599998,D,NaN,NaN,FM,Bio-Méd,G2,False,False,True,True,73.599998
7598,10263,2015-2016,72.400002,D,NaN,NaN,FM,Bio-Méd,G2,False,False,True,True,72.400002
8104,10577,2015-2016,73.300003,D,NaN,NaN,FM,Bio-Méd,G2,False,False,True,True,73.300003
8711,11269,2015-2016,74.000000,D,NaN,NaN,FM,Bio-Méd,G1,False,False,True,True,74.000000
8713,11272,2015-2016,71.699997,D,NaN,NaN,FM,Bio-Méd,G1,False,False,True,True,71.699997
9185,11767,2015-2016,NaN,AA,70.300003,D,FM,Bio-Méd,G1,False,False,True,False,70.300003

In [74]:
Reusite1erSess=medeDataset.apply(calculateReussite1Sessi,axis=1)

In [85]:
type(Reusite1erSess)

pandas.core.frame.DataFrame

In [89]:
medeDataset['Reusite1erSess']=Reusite1erSess

/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [91]:
medeDataset['ReusiteDistinc']=ReusiteDistinc

/Users/espyMur/Desktop/Memory-WorkingDir/memoryVenv/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [93]:
medeDataset.columns

Index([u'ID', u'ACADYEAR', u'PERC1', u'MENT1', u'PERC2', u'MENT2', u'FAC',
       u'OPT', u'PROM', u'Satisfaction', u'echec', u'distinction',
       u'Pass1stSession', u'PercFinal', u'Reusite1erSess', u'ReusiteDistinc'],
      dtype='object')

In [81]:
Reusite1erSess.loc[medeDataset.echec==True].get(0).value_counts()

False    78
Name: 0, dtype: int64

les nouvelles collones cree contiennent les rations:
    echec: Nous dit si l'edudiant a échouer dans une année académique
    resuite: Avec Distinction ous Satisfaction
    Session: 1ere Session ou pAs 
    Pourcentage Final:NB(Les étudiant qui sont AA au final : bref ceux qui n'ont pas de pourcentage on été remplacé avec un nobre aleatoire compris entre 45et 52')

In [125]:
medeDataset.columns

Index([u'ID', u'ACADYEAR', u'PERC1', u'MENT1', u'PERC2', u'MENT2', u'FAC',
       u'OPT', u'PROM', u'Satisfaction', u'echec', u'distinction',
       u'Pass1stSession', u'PercFinal'],
      dtype='object')

In [98]:
 def f(x):
    A=list(x['echec'])
    D=list(x['ReusiteDistinc'])
    S1=list(x['Reusite1erSess'])
    return pd.Series(dict(
     echec=int(A.count(True)),
     distinction=int(D.count(True)),
     Pass1stSession=int(S1.count(True)),
     CGPA=np.mean(x['PercFinal']),
     Nbre=int(len(x['ACADYEAR']))
    ))

In [99]:
medeDatasetRatio=medeDataset.groupby('ID').apply(f).reset_index()

In [100]:
medeDatasetRatio.head(5)

     ID       CGPA  Nbre  Pass1stSession  distinction  echec
0  1670  62.150000   2.0             1.0          0.0    0.0
1  9841  52.000000   1.0             0.0          0.0    1.0
2  9867  54.100000   2.0             0.0          0.0    1.0
3  9879  61.549999   2.0             1.0          0.0    0.0
4  9887  59.450001   2.0             1.0          0.0    0.0

In [101]:
medeDatasetRatio.loc[:,'Pass1stSession']=medeDatasetRatio.Pass1stSession/medeDatasetRatio.Nbre

In [102]:
medeDatasetRatio.loc[:,'distinction']=medeDatasetRatio.distinction/medeDatasetRatio.Nbre
medeDatasetRatio.loc[:,'echec']=medeDatasetRatio.echec/medeDatasetRatio.Nbre

In [103]:
medeDatasetRatio.head(5)

     ID       CGPA  Nbre  Pass1stSession  distinction  echec
0  1670  62.150000   2.0             0.5          0.0    0.0
1  9841  52.000000   1.0             0.0          0.0    1.0
2  9867  54.100000   2.0             0.0          0.0    0.5
3  9879  61.549999   2.0             0.5          0.0    0.0
4  9887  59.450001   2.0             0.5          0.0    0.0

Voila voici enfin notre ensemble de soertie : voici une description des colonnes qu'il comprend :
    - CGPA : La moyenne des pourcentages final Obtenu par l'etudiant
    - Pass1stSession: Nombré d'année que l'étudiant est passé en en 1 ere session divisé par les nombré d'années passées à la fac
    - distinction: Nombré d'années que l'étudiant a distingué divisé par les nombré d'années passées à la fac
    - echec: Nombré d'années que l'étudiant a échoué divisé par les nombré d'années passées à la fac

In [113]:
medeDatasetRatio.rename(columns={'Pass1stSession':'Ratio1ss','distinction':'RatioDist','echec':'RatioEchec'},inplace=True)

In [117]:
medeDataset=pd.merge(medeDataset,medeDatasetRatio[['ID','Ratio1ss','RatioDist','RatioEchec']],on='ID')

In [124]:
dasetOutMed=medeDatasetRatio

In [122]:
medeDataset[[u'ID', u'echec',
        u'PercFinal', u'Reusite1erSess', u'ReusiteDistinc',
       u'Ratio1ss', u'RatioDist', u'RatioEchec']]

,ID,echec,PercFinal,Reusite1erSess,ReusiteDistinc,Ratio1ss,RatioDist,RatioEchec
0,1670,False,65.099998,True,False,0.5,0.0,0.0
1,1670,False,59.200001,False,False,0.5,0.0,0.0
2,9841,True,52.000000,False,False,0.0,0.0,1.0
3,9867,False,59.200001,False,False,0.0,0.0,0.5
4,9867,True,49.000000,False,False,0.0,0.0,0.5
5,9879,False,64.199997,False,False,0.5,0.0,0.0
6,9879,False,58.900002,True,False,0.5,0.0,0.0
7,9887,False,60.000000,True,False,0.5,0.0,0.0
8,9887,False,58.900002,False,False,0.5,0.0,0.0
9,9891,False,56.299999,False,False,0.0,0.0,0.0
10,9891,False,55.500000,False,False,0.0,0.0,0.0
11,9909,True,52.000000,False,False,0.0,0.0,1.0
12,9915,False,62.299999,False,False,0.5,0.0,0.0
13,9915,False,59.900002,True,False,0.5,0.0,0.0
14,9916,False,66.400002,True,False,1.0,0.0,0.0
15,9916,False,66.199997,True,False,1.0,0.0,0.0
16,9942,False,62.500000,False,False,0.5,0.0,0.0
17,9942,False,59.200001,True,False,0.5,0.0,0.0
18,9950,False,61.200001,False,False,0.0,0.0,0.0
19,9965,True,47.000000,False,False,0.0,0.0,1.0
20,9975,True,51.000000,False,False,0.0,0.0,1.0
21,9978,False,62.700001,False,False,0.5,0.0,0.0
22,9978,False,62.700001,True,False,0.5,0.0,0.0
23,9983,True,47.000000,False,False,0.0,0.0,1.0
24,9993,True,52.700001,False,False,0.0,0.0,1.0
25,9998,False,65.199997,False,False,0.5,0.0,0.0
26,9998,False,64.699997,True,False,0.5,0.0,0.0
27,10001,False,63.099998,True,False,0.5,0.0,0.0
28,10001,False,61.000000,False,False,0.5,0.0,0.0
29,10008,False,61.599998,False,False,0.5,0.0,0.0
...,...,...,...,...,...,...,...,...
345,11998,False,59.000000,True,False,1.0,0.0,0.0
346,12013,False,59.299999,False,False,0.0,0.0,0.0
347,12039,True,48.700001,False,False,0.0,0.0,1.0
348,12049,False,64.599998,True,False,1.0,0.0,0.0
349,12051,False,68.800003,False,False,0.0,0.0,0.0
350,12062,True,45.000000,False,False,0.0,0.0,1.0
351,12069,False,58.599998,False,False,0.0,0.0,0.0
352,12070,False,61.500000,False,False,0.0,0.0,0.0
353,12075,False,64.400002,True,False,1.0,0.0,0.0
354,12082,False,61.099998,False,False,0.0,0.0,0.0
355,12110,False,65.900002,True,False,1.0,0.0,0.0
356,12119,True,48.000000,False,False,0.0,0.0,1.0
357,12120,True,55.000000,False,False,0.0,0.0,1.0
358,12132,False,61.500000,False,False,0.0,0.0,0.0
359,12140,False,56.099998,False,False,0.0,0.0,0.0
360,12141,False,63.400002,True,False,1.0,0.0,0.0
361,12143,False,60.200001,False,False,0.0,0.0,0.0
362,12145,False,59.000000,False,False,0.0,0.0,0.0
363,12146,False,58.799999,False,False,0.0,0.0,0.0
364,12148,False,58.099998,False,False,0.0,0.0,0.0
365,12150,False,67.800003,True,False,1.0,0.0,0.0
366,12159,False,63.599998,True,False,1.0,0.0,0.0
367,12164,False,62.299999,False,False,0.0,0.0,0.0
368,12174,True,42.000000,False,False,0.0,0.0,1.0
369,12175,True,46.000000,False,False,0.0,0.0,1.0
370,12182,False,61.400002,False,False,0.0,0.0,0.0
371,12187,False,56.599998,False,False,0.0,0.0,0.0
372,12191,True,51.000000,False,False,0.0,0.0,1.0
373,12205,False,59.099998,False,False,0.0,0.0,0.0
374,12252,False,61.599998,False,False,0.0,0.0,0.0

In [126]:
dasetOutMed.to_csv('DatasetOutMed.csv')